### ISSUE TITLE
[CMIP6 CMOR-ization & ESGF-publication] NorESM2-LM - ssp370-lowNTCF

### ISSUE THREAD

**Issue by DirkOlivie** [NorwegianClimateCentre/noresm2cmor#156] opened 2019-11-27 14:14 UTC
### Mandatory information:

**Full path to the case(s) of the experiment on NIRD**
/projects/NS9560K/FRAM/noresm/cases

**experiment_id**
ssp370-lowNTCF

**model_id**
NorESM2-LM

**CASENAME(s) and years to be CMORized**
NSSP370LOWNTCFfrc2_f19_tn14_20191118, 2015-2054

### Optional information

**parent_experiment_id**
historical

**parent_experiment_rip**
r1i1p1f1

**parent_time_units**
'days since 1850-01-01'

**branch_method**
'Hybrid-restart from year 2015-01-01 of historical'

**other information**

**Comment by YanchunHe** [comment] 2019-12-12 07:48
namelists and scripts have been created.

When the output is synced to NIRD. please start the job by:

```bash
cd /projects/NS9560K/cmor/noresm2cmor/namelists/CMIP6_NorESM2-LM/ssp370-lowNTCF
./cmor.sh -m=NorESM2-LM -e=ssp370-lowNTCF -v=v20191108 &>>logs/cmor.log.v20191108 &
```

**Comment by jgriesfeller** [comment] 2019-12-12 08:46
rsync has been started. Since it's only 1.8 TB we should be able to get this done today.

**Comment by jgriesfeller** [comment] 2019-12-12 12:30
transfer has finished; starting job on login2

**Comment by jgriesfeller** [comment] 2019-12-12 12:45
This also did not work unfortunately:
START CMOR...       
Thu Dec 12 13:31:06 CET 2019             
                    
CaseName: NSSP370LOWNTCFfrc2_f19_tn14_20191118
expid   : ssp370-lowNTCF
version : v20191108
real    : 1
manpath: can't set the locale; make sure $LC_* and $LANG are correct
2015 2020
2021 2030
2031 2040
2041 2050
2051
         
CMOR DONE
Thu Dec 12 13:38:07 CET 2019  
~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~
PrePARE QC CHECK... 
/projects/NS9560K/cmor/noresm2cmor/workflow/cmorQC.sh: line 53: cd: /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF: No such file or directory
0 files           
                    
/projects/NS9560K/cmor/noresm2cmor/workflow/cmorQC.sh: line 2: v20191108.QCreport: No such file or directory
         
QC DONE  
~~~~~~~~~
         
~~~~~~~~~~~~~~~~
LINKING FILES...
                
.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108
find: '.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108': No such file or directory
Total 0 files
cdo showattribute (Abort): Too few streams specified! Operator needs 1 input and 0 output streams.
/projects/NS9560K/cmor/noresm2cmor/workflow/cmorLink.sh: line 100: .cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108.links: No such file or directory

                       
LINKS DONE             
~~~~~~~~~~~~~~~~~~~~~~~
                       
~~~~~~~~~~~~~~~~~~~~~~~
UPDATING SHA256SUM...  
                       
.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108
                       
ERROR: /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108.links does not exits.

**Comment by YanchunHe** [comment] 2019-12-12 12:55
please try again.

**Comment by jgriesfeller** [comment] 2019-12-12 13:19
seems to work now
Where is the output supposed to go?

**Comment by YanchunHe** [comment] 2019-12-12 13:21
/tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-LM/

**Comment by jgriesfeller** [comment] 2019-12-12 15:38
cmorisation job has finished, but for some reason only the years 2015 to 2020 have been cmorised.
Yanchun, any idea why?

**Comment by jgriesfeller** [comment] 2019-12-13 08:52
There's not even a checkcmorout.sh in the folder /projects/NS9560K/cmor/noresm2cmor/namelists/CMIP6_NorESM2-LM/ssp370-lowNTCF
I have no idea what to do at this point

**Comment by jgriesfeller** [comment] 2019-12-13 11:58
I started the job again after I understood it a bit better. This time it at least started the 2nd period as well.
I more and more think that the `runcmor` command dies too quickly when something goes wrong.

**Comment by YanchunHe** [comment] 2019-12-13 15:44
checkcmorout.sh is not essential to run the cmor job, but used for check the results when it is finished or stopped.

I created a checkcmout.sh now, simply from previous template, for example, ssp370/checkoutcmor.sh and modify the years according to cmor.sh

yanchun@login-nird-1:/projects/NS9560K/cmor/noresm2cmor/namelists/CMIP6_NorESM2-LM/ssp370-lowNTCF
$ ./checkcmorout.sh
real:	r1i1p1f1
Ofx, fx, etc	10
yyyy1	yyyy2	nf
2015	2020	542
2021	2030	542
2031	2040	542
2041	2050	542
2051	2054	0
Total:		2178
Wrong files:

Looks like only 2051-2054 is not cmorized. But there are Unfinished/wrong files

Unfinished files:
37M Dec 13 16:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/airmass_AERmon_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gnPUPLnz22230.nc
263M Dec 12 18:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/co3satarag_Omon_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_grjxED2J86002.nc
539M Dec 12 18:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/co3satcalc_Omon_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_grmnaohT86004.nc
138M Dec 13 16:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/dms_AERmon_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gnIihHMg22229.nc
1.3M Dec 13 16:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/emidms_AERmon_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gnY4Z89222233.nc
41K Dec 13 16:37 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/emidust_AERmon_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gni7IelC22234.nc
104M Dec 13 16:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/mmraerh2o_AERmon_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gnnpFwRM22236.nc
665M Dec 12 18:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/mrsol_Eday_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gnlihSsO85998.nc
43K Dec 13 16:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/od550aer_AERmon_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gnvcZLNj22231.nc
190M Dec 12 18:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/ph_Omon_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_grfhNxDb86000.nc
62M Dec 12 18:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/rsuscs_CFday_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gn3WPJuT86001.nc
4.0M Dec 12 18:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/siv_SIday_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gnFpfeq486005.nc
48M Dec 13 16:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/ua_AERmon_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gnbrHZ1g22235.nc
1.1G Dec 12 18:38 /projects/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108/wap_CFday_NorESM2-LM_ssp370-lowNTCF_r1i1p1f1_gnwtJ3cd85999.nc

But certainly, files created on Dec 12 should be removed, before it reaches cmorPost.sh stage.

And It is liklely that your noresm2cmor3_mpi job is processing those period 2031-2041, which are already cmorized.

Please use `ps ux |less` and see if it is processing the periods that have been cmorzied.

If so, kill the program.  run checkcmorout.sh, remove the unfinished files and lanunch the job again only for year 2051-2054. Thanks!

**Comment by jgriesfeller** [comment] 2019-12-13 23:37
(base) [jang@login-nird-1 ssp370-lowNTCF]$ ./checkcmorout.sh
real:	r1i1p1f1
Ofx, fx, etc	10
yyyy1	yyyy2	nf
2015	2020	542
2021	2030	542
2031	2040	542
2041	2050	542
2051	2054	0
Total:		2178

years 2015 to 2050 are cmorised, but the last 5 years are missing.

It turned out to be an error in the year definition in the cmor.sh script

Running the last 5 years now

**Comment by jgriesfeller** [comment] 2019-12-14 14:48
This should be finally finished:
(base) [jang@login-nird-3 ssp370-lowNTCF]$ pwd
/projects/NS9560K/cmor/noresm2cmor/namelists/CMIP6_NorESM2-LM/ssp370-lowNTCF
(base) [jang@login-nird-3 ssp370-lowNTCF]$ ./checkcmorout.sh 
real:	r1i1p1f1
Ofx, fx, etc	10
yyyy1	yyyy2	nf
2015	2020	542
2021	2030	542
2031	2040	542
2041	2050	542
2051	2054	542
Total:		2720

Alok, please publish.

**Comment by YanchunHe** [comment] 2019-12-14 15:42
Hi Jan,

The cmorization is finished, but some more steps to create QCreport, links and sha256sum are not finished yet, so it is not ready to publish.

I think the problem is before you lanched again the cmor_tmp.sh, you didt not remove the unfinished files by running the checkcmorout.sh. These unfinished file will exist when the cmoriztion is over. And the cmorQC will find there are errors, so that the script will not proceed with making links and sha256sum (otherwise, the sha256sum and links will include these wrong files).

Those unfinished files are not removed according to your post. So please run the cmorPost.sh again.

When it done, cross check the QCreport, checkcmorout.sh results, number of links and sha256sum.

If they all matches with each other. Post about the information of cmorzied data (see historical as example, label ESGF publish and assign Alok).

**Comment by jgriesfeller** [comment] 2019-12-14 23:37
did as suggested:
```
(base) [jang@login-nird-3 workflow]$ ./cmorPost.sh -m=NorESM2-LM -e=ssp370-lowNTCF -v=v20191108
~~~~~~~~~~~~~~~~~~~~
PrePARE QC CHECK... 
2720 files           

(base) [jang@login-nird-3 workflow]$ ./cmorQC.sh -m=NorESM2-LM -e=ssp370-lowNTCF -v=v20191108
(base) [jang@login-nird-3 workflow]$ ./cmorLink.sh -m=NorESM2-LM -e=ssp370-lowNTCF -v=v20191108
~~~~~~~~~~~~~~~~
LINKING FILES...
                
.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108
Total 2720 files

                       
LINKS DONE             
~~~~~~~~~~~~~~~~~~~~~~~
(base) [jang@login-nird-3 workflow]$ ./cmorSha256sum.sh -m=NorESM2-LM -e=ssp370-lowNTCF -v=v20191108
                       
~~~~~~~~~~~~~~~~~~~~~~~
UPDATING SHA256SUM...  
                       
.cmorout/NorESM2-LM/ssp370-lowNTCF/v20191108
Total 2720 files
./cmorSha256sum.sh: line 110: cannot redirect standard input from /dev/null: Operation not permitted


                
SHA256SUM DONE         
~~~~~~~~~~~~~~~~~~~~~~~

```
Should be done now

**Comment by jgriesfeller** [comment] 2019-12-16 12:58
cmorized

data path

    /tos-project1/NS9034K/CMIP6/.cmorout/NorESM2-LM/ssp370-lowNTCF/

version

    v20191108

sha256sum

   I am not entirely sure where to find the sha256 sums, but the script ran

Alok, if you cannot find it, please ignore this and assign it back to Yanchun

**Comment by monsieuralok** [comment] 2019-12-18 19:45
@DirkOlivie @YanchunHe @jgriesfeller published

**Closed by monsieuralok** 2019-12-18 19:45 UTC
Labels: CMORize, ESGF publish, FRAM, Rsync, started

**Comment by YanchunHe** [comment] 2020-01-14 14:07
(refer to @DirkOlivie )
There is an issue with the setup of the ssp370-lowNTCF simulations.  I have set them up such that GHGs follow ssp370-lowNTCF, but they should have followed the standard ssp370.
The published data to ESGF should be retracted (by @monsieuralok )
Corrected simulation will be done and requested to be cmorized (in separate GitHub issues).

**Comment by monsieuralok** [comment] 2020-01-14 14:12
@DirkOlivie @YanchunHe  already retracted
